const themes = {
    "Action A" : [
      {
        name : "cry",
        image : "./assets/img/cry.jpg",
        translate: "плакать",
      },
      {
        name : "dance",
        image : "./assets/img/dance.jpg",
        translate: "танцевать",
      },
      {
        name : "dive",
        image : "./assets/img/dive.jpg",
        translate: "погружаться",
      },
      {
        name : "draw",
        image : "./assets/img/draw.jpg",
        translate: "рисовать",
      },
      {
        name : "fish",
        image : "./assets/img/fish.jpg",
        translate: "рыбачить",
      },
      {
        name : "fly",
        image : "./assets/img/fly.jpg",
        translate: "летать",
      },
      {
        name : "hug",
        image : "./assets/img/hug.jpg",
        translate: "обнимать",
  
      },
      {
        name : "jump",
        image : "./assets/img/jump.jpg",
        translate: "прыгать",
      },
    ],
    "Action B" : [
      {
        name : "open",
        image : "./assets/img/open.jpg",
        translate: "открывать",
      },
      {
        name : "play",
        image : "./assets/img/play.jpg",
        translate: "играть",
      },
      {
        name : "point",
        image : "./assets/img/point.jpg",
        translate: "указывать",
      },
      {
        name : "ride",
        image : "./assets/img/ride.jpg",
        translate: "ездить",
      },
      {
        name : "run",
        image : "./assets/img/run.jpg",
        translate: "бежать",
      },
      {
        name : "sing",
        image : "./assets/img/sing.jpg",
        translate: "петь",
      },
      {
        name : "skip",
        image : "./assets/img/skip.jpg",
        translate: "пропускать, прыгать",
      },
      {
        name : "swim",
        image : "./assets/img/swim.jpg",
        translate: "плавать",
      },
    ],
    "Clothes" : [
      {
        name : "skirt",
        image : "./assets/img/skirt.jpg",
        translate: "юбка",
      },
      {
        name : "pants",
        image : "./assets/img/pants.jpg",
        translate: "брюки",
      },
      {
        name : "blouse",
        image : "./assets/img/blouse.jpg",
        translate: "блузка",
      },
      {
        name : "dress",
        image : "./assets/img/dress.jpg",
        translate: "платье",
      },
      {
        name : "boot",
        image : "./assets/img/boot.jpg",
        translate: "ботинки",
      },
      {
        name : "shirt",
        image : "./assets/img/shirt.jpg",
        translate: "рубашка",
      },
      {
        name : "coat",
        image : "./assets/img/coat.jpg",
        translate: "пальто",
      },
      {
        name : "shoe",
        image : "./assets/img/shoe.jpg",
        translate: "туфли",
      },
    ],
    "Adjective" : [
      {
        name : "big",
        image : "./assets/img/big.jpg",
        translate: "большой",
      },
      {
        name : "small",
        image : "./assets/img/small.jpg",
        translate: "маленький",
      },
      {
        name : "fast",
        image : "./assets/img/fast.jpg",
        translate: "быстрый",
      },
      {
        name : "slow",
        image : "./assets/img/slow.jpg",
        translate: "медленный",
      },
      {
        name : "friendly",
        image : "./assets/img/friendly.jpg",
        translate: "дружелюбный",
      },
      {
        name : "unfriendly",
        image : "./assets/img/unfriendly.jpg",
        translate: "недружелюбный",
      },
      {
        name : "young",
        image : "./assets/img/young.jpg",
        translate: "молодой",
      },
      {
        name : "old",
        image : "./assets/img/old.jpg",
        translate: "старый",
      },
    ],
    "Adjective" : [
      {
        name : "big",
        image : "./assets/img/big.jpg",
        translate: "большой",
      },
      {
        name : "small",
        image : "./assets/img/small.jpg",
        translate: "маленький",
      },
      {
        name : "fast",
        image : "./assets/img/fast.jpg",
        translate: "быстрый",
      },
      {
        name : "slow",
        image : "./assets/img/slow.jpg",
        translate: "медленный",
      },
      {
        name : "friendly",
        image : "./assets/img/friendly.jpg",
        translate: "дружелюбный",
      },
      {
        name : "unfriendly",
        image : "./assets/img/unfriendly.jpg",
        translate: "недружелюбный",
      },
      {
        name : "young",
        image : "./assets/img/young.jpg",
        translate: "молодой",
      },
      {
        name : "old",
        image : "./assets/img/old.jpg",
        translate: "старый",
      },
    ],
    "Animal A" : [
      {
        name : "cat",
        image : "./assets/img/cat.jpg",
        translate: "кошка",
      },
      {
        name : "chick",
        image : "./assets/img/chick.jpg",
        translate: "цыпленок",
      },
      {
        name : "chicken",
        image : "./assets/img/chicken.jpg",
        translate: "курица",
      },
      {
        name : "dog",
        image : "./assets/img/dog.jpg",
        translate: "собака",
      },
      {
        name : "horse",
        image : "./assets/img/horse.jpg",
        translate: "лошадь",
      },
      {
        name : "rabbit",
        image : "./assets/img/rabbit.jpg",
        translate: "кролик",
      },
      {
        name : "sheep",
        image : "./assets/img/sheep.jpg",
        translate: "овца",
      },
      {
        name : "pig",
        image : "./assets/img/pig.jpg",
        translate: "поросенок",
      },
    ],
    "Animal B" : [
      {
        name : "bird",
        image : "./assets/img/bird.jpg",
        translate: "птица",
      },
      {
        name : "elephant",
        image : "./assets/img/elephant.jpg",
        translate: "слон",
      },
      {
        name : "frog",
        image : "./assets/img/frog.jpg",
        translate: "лягушка",
      },
      {
        name : "giraffe",
        image : "./assets/img/giraffe.jpg",
        translate: "жираф",
      },
      {
        name : "lion",
        image : "./assets/img/lion.jpg",
        translate: "лев",
      },
      {
        name : "mouse",
        image : "./assets/img/mouse.jpg",
        translate: "мышь",
      },
      {
        name : "turtle",
        image : "./assets/img/turtle.jpg",
        translate: "черепаха",
      },
      {
        name : "dolphin",
        image : "./assets/img/dolphin.jpg",
        translate: "дельфин",
      },
    ],
    "Public" : [
      {
        name : "cinema",
        image : "./assets/img/cinema.jpg",
        translate: "кино",
      },
      {
        name : "theatre",
        image : "./assets/img/theatre.jpg",
        translate: "театр",
      },
      {
        name : "store",
        image : "./assets/img/store.jpg",
        translate: "магазин",
      },
      {
        name : "park",
        image : "./assets/img/park.jpg",
        translate: "парк",
      },
      {
        name : "school",
        image : "./assets/img/school.jpg",
        translate: "школа",
      },
      {
        name : "festival",
        image : "./assets/img/festival.jpg",
        translate: "фестиваль",
      },
      {
        name : "beach",
        image : "./assets/img/beach.jpg",
        translate: "пляж",
      },
      {
        name : "restaurant",
        image : "./assets/img/restaurant.jpg",
        translate: "ресторан",
      },
    ],
    "Sport" : [
      {
        name : "football",
        image : "./assets/img/football.jpg",
        translate: "футбол",
      },
      {
        name : "hockey",
        image : "./assets/img/hockey.jpg",
        translate: "хоккей",
      },
      {
        name : "tennis",
        image : "./assets/img/tennis.jpg",
        translate: "теннис",
      },
      {
        name : "sprint",
        image : "./assets/img/sprint.jpg",
        translate: "спринт",
      },
      {
        name : "volleyball",
        image : "./assets/img/volleyball.jpg",
        translate: "волейбол",
      },
      {
        name : "baseball",
        image : "./assets/img/baseball.jpg",
        translate: "бейсбол",
      },
      {
        name : "race",
        image : "./assets/img/race.jpg",
        translate: "гонки",
      },
      {
        name : "basketball",
        image : "./assets/img/basketball.jpg",
        translate: "баксетбол",
      },
    ],
    
  
  };

const statistic = {
  "cry": {
      "category": "Action A",
      "word": "cry",
      "translate": "плакать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "dance": {
      "category": "Action A",
      "word": "dance",
      "translate": "танцевать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "dive": {
      "category": "Action A",
      "word": "dive",
      "translate": "погружаться",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "draw": {
      "category": "Action A",
      "word": "draw",
      "translate": "рисовать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "fish": {
      "category": "Action A",
      "word": "fish",
      "translate": "рыбачить",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "fly": {
      "category": "Action A",
      "word": "fly",
      "translate": "летать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "hug": {
      "category": "Action A",
      "word": "hug",
      "translate": "обнимать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "прыгать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "open": {
      "category": "Action B",
      "word": "open",
      "translate": "открывать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "play": {
      "category": "Action B",
      "word": "play",
      "translate": "играть",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "point": {
      "category": "Action B",
      "word": "point",
      "translate": "указывать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "ride": {
      "category": "Action B",
      "word": "ride",
      "translate": "ездить",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "run": {
      "category": "Action B",
      "word": "run",
      "translate": "бежать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "sing": {
      "category": "Action B",
      "word": "sing",
      "translate": "петь",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "skip": {
      "category": "Action B",
      "word": "skip",
      "translate": "пропускать, прыгать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "swim": {
      "category": "Action B",
      "word": "swim",
      "translate": "плавать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "skirt": {
      "category": "Clothes",
      "word": "skirt",
      "translate": "юбка",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "pants": {
      "category": "Clothes",
      "word": "pants",
      "translate": "брюки",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "blouse": {
      "category": "Clothes",
      "word": "blouse",
      "translate": "блузка",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "dress": {
      "category": "Clothes",
      "word": "dress",
      "translate": "платье",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "boot": {
      "category": "Clothes",
      "word": "boot",
      "translate": "ботинки",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "shirt": {
      "category": "Clothes",
      "word": "shirt",
      "translate": "рубашка",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "coat": {
      "category": "Clothes",
      "word": "coat",
      "translate": "пальто",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "shoe": {
      "category": "Clothes",
      "word": "shoe",
      "translate": "туфли",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "big": {
      "category": "Adjective",
      "word": "big",
      "translate": "большой",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "small": {
      "category": "Adjective",
      "word": "small",
      "translate": "маленький",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "fast": {
      "category": "Adjective",
      "word": "fast",
      "translate": "быстрый",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "slow": {
      "category": "Adjective",
      "word": "slow",
      "translate": "медленный",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "friendly": {
      "category": "Adjective",
      "word": "friendly",
      "translate": "дружелюбный",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "unfriendly": {
      "category": "Adjective",
      "word": "unfriendly",
      "translate": "недружелюбный",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "young": {
      "category": "Adjective",
      "word": "young",
      "translate": "молодой",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "old": {
      "category": "Adjective",
      "word": "old",
      "translate": "старый",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "cat": {
      "category": "Animal A",
      "word": "cat",
      "translate": "кошка",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "chick": {
      "category": "Animal A",
      "word": "chick",
      "translate": "цыпленок",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "chicken": {
      "category": "Animal A",
      "word": "chicken",
      "translate": "курица",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "dog": {
      "category": "Animal A",
      "word": "dog",
      "translate": "собака",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "horse": {
      "category": "Animal A",
      "word": "horse",
      "translate": "лошадь",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "rabbit": {
      "category": "Animal A",
      "word": "rabbit",
      "translate": "кролик",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "sheep": {
      "category": "Animal A",
      "word": "sheep",
      "translate": "овца",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "pig": {
      "category": "Animal A",
      "word": "pig",
      "translate": "поросенок",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "bird": {
      "category": "Animal B",
      "word": "bird",
      "translate": "птица",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "elephant": {
      "category": "Animal B",
      "word": "elephant",
      "translate": "слон",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "frog": {
      "category": "Animal B",
      "word": "frog",
      "translate": "лягушка",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "giraffe": {
      "category": "Animal B",
      "word": "giraffe",
      "translate": "жираф",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "lion": {
      "category": "Animal B",
      "word": "lion",
      "translate": "лев",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "mouse": {
      "category": "Animal B",
      "word": "mouse",
      "translate": "мышь",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "turtle": {
      "category": "Animal B",
      "word": "turtle",
      "translate": "черепаха",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "dolphin": {
      "category": "Animal B",
      "word": "dolphin",
      "translate": "дельфин",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "cinema": {
      "category": "Public",
      "word": "cinema",
      "translate": "кино",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "theatre": {
      "category": "Public",
      "word": "theatre",
      "translate": "театр",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "store": {
      "category": "Public",
      "word": "store",
      "translate": "магазин",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "park": {
      "category": "Public",
      "word": "park",
      "translate": "парк",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "school": {
      "category": "Public",
      "word": "school",
      "translate": "школа",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "festival": {
      "category": "Public",
      "word": "festival",
      "translate": "фестиваль",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "beach": {
      "category": "Public",
      "word": "beach",
      "translate": "пляж",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "restaurant": {
      "category": "Public",
      "word": "restaurant",
      "translate": "ресторан",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "football": {
      "category": "Sport",
      "word": "football",
      "translate": "футбол",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "hockey": {
      "category": "Sport",
      "word": "hockey",
      "translate": "хоккей",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "tennis": {
      "category": "Sport",
      "word": "tennis",
      "translate": "теннис",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "sprint": {
      "category": "Sport",
      "word": "sprint",
      "translate": "спринт",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "volleyball": {
      "category": "Sport",
      "word": "volleyball",
      "translate": "волейбол",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "baseball": {
      "category": "Sport",
      "word": "baseball",
      "translate": "бейсбол",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "race": {
      "category": "Sport",
      "word": "race",
      "translate": "гонки",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  }, "basketball": {
      "category": "Sport",
      "word": "basketball",
      "translate": "баксетбол",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
  },
};

/* const statistic = {
    "cry": {
        "category": "Action A",
        "word": "cry",
        "translate": "плакать",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "dance": {
        "category": "Action A",
        "word": "dance",
        "translate": "танцевать",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "dive": {
        "category": "Action A",
        "word": "dive",
        "translate": "погружаться",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "draw": {
        "category": "Action A",
        "word": "draw",
        "translate": "рисовать",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "fish": {
        "category": "Action A",
        "word": "fish",
        "translate": "рыбачить",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "fly": {
        "category": "Action A",
        "word": "fly",
        "translate": "летать",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "hug": {
        "category": "Action A",
        "word": "hug",
        "translate": "обнимать",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "jump": {
        "category": "Action A",
        "word": "jump",
        "translate": "пыргать",
        "clickTrain": 0,
        "clickCorrect": 0,
        "clickWrong": 0,
    },
    "open": {
      "category": "Action B",
      "word": "open",
      "translate": "открывать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "play": {
      "category": "Action B",
      "word": "play",
      "translate": "играть",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "point": {
      "category": "Action B",
      "word": "point",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "ride": {
      "category": "Action B",
      "word": "ride",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "run": {
      "category": "Action B",
      "word": "run",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "sing": {
      "category": "Action B",
      "word": "sing",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "skip": {
      "category": "Action B",
      "word": "skip",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "swim": {
      "category": "Action B",
      "word": "swim",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
    "jump": {
      "category": "Action A",
      "word": "jump",
      "translate": "пыргать",
      "clickTrain": 0,
      "clickCorrect": 0,
      "clickWrong": 0,
    },
}
     */  